version: '3.8'
services:
  test:
    build: .
    volumes:
      - ./:/usr/src/app
    # Expose ports if needed for debug, etc
    command: ["npx", "cucumber-js", "--require-module", "ts-node/register", "--require", "features/steps/**/*.ts", "features"]
